version: '3.1'
services :
  database:
    container_name: postgreSQL
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbjs
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on: 
      - database